INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday,createdAt, updatedAt) values ('Jane', 'Austen','jane@gmail.com','CRN',true,true,true,true,true,true,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('danny', 'mestawat','danny@gmail.com','CRN',true,false,true,false,true,false,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Charles', 'Rainey','Charles@gmail.com','CRN',false,true,false,true,false,true,false,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Mary', 'Nash','Mary@gmail.com','CRN',false,false,false,false,true,true,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Peter', 'Lillis','Peter@gmail.com','CRN',true,true,true,true,false,false,false,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday,createdAt, updatedAt) values ('Joe', 'Bachie','joeB@gmail.com','CRN',true,true,true,true,true,false,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Genard', 'Arnold','genard@gmail.com','CRN',true,false,true,false,true,false,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Derek', 'Barnett','derekbarnett@gmail.com','CRN',false,true,false,true,false,true,false,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Shaun', 'Bradley','shaunbradley@gmail.com','CRN',false,false,false,false,true,true,true,"2021-03-02 17:47:12", "2021-03-02 17:47:12");
INSERT INTO providers (provider_First_name, provider_last_name,email,license,monday,tuesday,wednesday,thursday,friday,saturday,sunday, createdAt, updatedAt) values ('Corey', 'Clement','coreyclement@gmail.com','CRN',true,true,true,true,false,false,false,"2021-03-02 17:47:12", "2021-03-02 17:47:12");

-- INSERT INTO Patient (title, authorId) values ('Pride and Prejudice', 1);
-- INSERT INTO Patient (title, authorId) values ('Emma', 1);
-- INSERT INTO Patient (title, authorId) values ('The Adventures of Tom Sawyer', 2);
-- INSERT INTO Patient (title, authorId) values ('Adventures of Huckleberry Finn', 2);
-- INSERT INTO Patient (title, authorId) values ('Alice''s Adventures in Wonderland', 3);
-- INSERT INTO Patient (title, authorId) values ('Dracula', null);